# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\".\n\x05\x42\x61tch\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x17\n\x05\x62\x61tch\x18\x02 \x03(\x0b\x32\x08.Request\"\xc1\x02\n\x07Request\x12\x13\n\x04type\x18\x01 \x01(\x0e\x32\x05.Type\x12\x0b\n\x03rid\x18\x02 \x01(\r\x12\x0b\n\x03sub\x18\x03 \x03(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\t\x12 \n\x04info\x18\n \x03(\x0b\x32\x12.Request.InfoEntry\x12\x1e\n\x03msg\x18\x0b \x03(\x0b\x32\x11.Request.MsgEntry\x12\x16\n\x0escaling_factor\x18\x0c \x01(\x02\x12\r\n\x05\x62ytes\x18\x0f \x01(\x0c\x12\x0b\n\x03res\x18\x10 \x03(\t\x12\x19\n\x05\x62\x65gin\x18\x14 \x01(\x0b\x32\n.Timestamp\x12\x0f\n\x07latency\x18\x15 \x03(\x02\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a*\n\x08MsgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"$\n\x05Reply\x12\x0c\n\x04\x66lag\x18\x01 \x01(\r\x12\r\n\x05qsize\x18\x02 \x01(\r\"2\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x05*\xa7\x01\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x10\n\x0cTYPE_CONNECT\x10\x01\x12\x10\n\x0cTYPE_REQUEST\x10\x02\x12\x0f\n\x0bTYPE_RESULT\x10\x03\x12\x10\n\x0cTYPE_CONTROL\x10\x04\x12\x10\n\x0cTYPE_MESSAGE\x10\x05\x12\x12\n\x0eTYPE_HEARTBEAT\x10\x06\x12\x0e\n\nTYPE_DUMMY\x10\x07\x12\x10\n\x0cTYPE_SCALING\x10\x08\x32M\n\tInference\x12!\n\x0bSendRequest\x12\x08.Request\x1a\x06.Reply\"\x00\x12\x1d\n\tSendBatch\x12\x06.Batch\x1a\x06.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REQUEST_INFOENTRY._options = None
    _REQUEST_INFOENTRY._serialized_options = b'8\001'
    _REQUEST_MSGENTRY._options = None
    _REQUEST_MSGENTRY._serialized_options = b'8\001'
    _TYPE._serialized_start = 480
    _TYPE._serialized_end = 647
    _BATCH._serialized_start = 17
    _BATCH._serialized_end = 63
    _REQUEST._serialized_start = 66
    _REQUEST._serialized_end = 387
    _REQUEST_INFOENTRY._serialized_start = 300
    _REQUEST_INFOENTRY._serialized_end = 343
    _REQUEST_MSGENTRY._serialized_start = 345
    _REQUEST_MSGENTRY._serialized_end = 387
    _REPLY._serialized_start = 389
    _REPLY._serialized_end = 425
    _TIMESTAMP._serialized_start = 427
    _TIMESTAMP._serialized_end = 477
    _INFERENCE._serialized_start = 649
    _INFERENCE._serialized_end = 726
# @@protoc_insertion_point(module_scope)
