# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
                '/Inference/SendRequest',
                request_serializer=service__pb2.Request.SerializeToString,
                response_deserializer=service__pb2.Reply.FromString,
                )
        self.SendBatch = channel.unary_unary(
                '/Inference/SendBatch',
                request_serializer=service__pb2.Batch.SerializeToString,
                response_deserializer=service__pb2.Reply.FromString,
                )


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRequest(self, request, context):
        """todo: ref - https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRequest,
                    request_deserializer=service__pb2.Request.FromString,
                    response_serializer=service__pb2.Reply.SerializeToString,
            ),
            'SendBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatch,
                    request_deserializer=service__pb2.Batch.FromString,
                    response_serializer=service__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/SendRequest',
            service__pb2.Request.SerializeToString,
            service__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/SendBatch',
            service__pb2.Batch.SerializeToString,
            service__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
